language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
env:
  - DB=sqlite BENCHMARK=1
  - DB=mysql BENCHMARK=1
  - DB=postgresql BENCHMARK=1
script:
  - cd test
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - mysql -e 'create database my_app_test'
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs
addons:
  code_climate:
    repo_token: 658424787fad8258ea72d97fb3d6dea29f3fb023d8d1a894173d9575609a4d88
